#!/usr/bin/python3

import os
import sys

import jstest

from PyQt6.QtWidgets import QApplication

class t1:
    search_term = 'example'
    n_results = 101
    n_links = 101
    n_highlights = 117

class t2:
    search_term = 'examples'
    n_results = 92
    n_links = 92
    n_highlights = 25

class t3:
    search_term = 'graph'
    n_results = 39
    n_links = 39
    n_highlights = 135

if __name__ == '__main__':
    if not os.getenv('DISPLAY'):
        raise RuntimeError('These tests require access to an X server')
    app = QApplication(sys.argv)
    [build_directory] = sys.argv[1:]
    build_directory = os.path.abspath(build_directory)
    n_failures = 0
    for testcase in t1, t2, t3:
        failures = jstest.test_directory(build_directory, testcase).failures
        n_failures += len(failures)
    sys.exit(n_failures > 0)

# vim:ts=4 sw=4 et
